-- DropForeignKey
ALTER TABLE "CONTACTE_CLIENTS" DROP CONSTRAINT "CONTACTE_CLIENTS_id_client_fkey";

-- DropForeignKey
ALTER TABLE "HORARIS_TORNS" DROP CONSTRAINT "HORARIS_TORNS_id_torn_fkey";

-- DropForeignKey
ALTER TABLE "PLAT_RESTAURANT" DROP CONSTRAINT "PLAT_RESTAURANT_id_plat_fkey";

-- DropForeignKey
ALTER TABLE "PLAT_RESTAURANT" DROP CONSTRAINT "PLAT_RESTAURANT_id_restaurant_fkey";

-- DropForeignKey
ALTER TABLE "RESERVES" DROP CONSTRAINT "RESERVES_id_restaurant_fkey";

-- DropForeignKey
ALTER TABLE "RESERVES" DROP CONSTRAINT "RESERVES_id_taula_restaurant_fkey";

-- DropForeignKey
ALTER TABLE "RESERVES" DROP CONSTRAINT "RESERVES_id_torn_fkey";

-- DropForeignKey
ALTER TABLE "TAULES_RESTAURANT" DROP CONSTRAINT "TAULES_RESTAURANT_id_restaurant_fkey";

-- DropForeignKey
ALTER TABLE "TAULES_RESTAURANT" DROP CONSTRAINT "TAULES_RESTAURANT_id_zona_fkey";

-- DropForeignKey
ALTER TABLE "TORNS" DROP CONSTRAINT "TORNS_id_restaurant_fkey";

-- DropForeignKey
ALTER TABLE "ZONES" DROP CONSTRAINT "ZONES_id_restaurant_fkey";

-- AddForeignKey
ALTER TABLE "TAULES_RESTAURANT" ADD CONSTRAINT "TAULES_RESTAURANT_id_zona_fkey" FOREIGN KEY ("id_zona") REFERENCES "ZONES"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAULES_RESTAURANT" ADD CONSTRAINT "TAULES_RESTAURANT_id_restaurant_fkey" FOREIGN KEY ("id_restaurant") REFERENCES "RESTAURANTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ZONES" ADD CONSTRAINT "ZONES_id_restaurant_fkey" FOREIGN KEY ("id_restaurant") REFERENCES "RESTAURANTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RESERVES" ADD CONSTRAINT "RESERVES_id_taula_restaurant_fkey" FOREIGN KEY ("id_taula_restaurant") REFERENCES "TAULES_RESTAURANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RESERVES" ADD CONSTRAINT "RESERVES_id_restaurant_fkey" FOREIGN KEY ("id_restaurant") REFERENCES "RESTAURANTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RESERVES" ADD CONSTRAINT "RESERVES_id_torn_fkey" FOREIGN KEY ("id_torn") REFERENCES "TORNS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TORNS" ADD CONSTRAINT "TORNS_id_restaurant_fkey" FOREIGN KEY ("id_restaurant") REFERENCES "RESTAURANTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HORARIS_TORNS" ADD CONSTRAINT "HORARIS_TORNS_id_torn_fkey" FOREIGN KEY ("id_torn") REFERENCES "TORNS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PLAT_RESTAURANT" ADD CONSTRAINT "PLAT_RESTAURANT_id_restaurant_fkey" FOREIGN KEY ("id_restaurant") REFERENCES "RESTAURANTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PLAT_RESTAURANT" ADD CONSTRAINT "PLAT_RESTAURANT_id_plat_fkey" FOREIGN KEY ("id_plat") REFERENCES "PLATS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CONTACTE_CLIENTS" ADD CONSTRAINT "CONTACTE_CLIENTS_id_client_fkey" FOREIGN KEY ("id_client") REFERENCES "CLIENTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;
